language: python
python:
  - "2.7"
  - "2.6"
before_install:
 - sudo sh -c "echo 'deb http://dev.monetdb.org/downloads/deb/ precise monetdb' > /etc/apt/sources.list.d/monetdb.list"
 - wget --output-document=- http://dev.monetdb.org/downloads/MonetDB-GPG-KEY | sudo apt-key add -
 - sudo apt-get update -qq
 - sudo apt-get install -qq monetdb5-sql monetdb-client
 - sudo usermod -a -G monetdb $USER
 - sudo sh -c "echo 'STARTUP=ues\nDBFARM=/var/lib/monetdb\n' > /etc/default/monetdb5-sql"
 - sudo service monetdb5-sql start
install: pip install -r requirements.txt --use-mirrors
script:  python tests/tests.py
